/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/telemetry/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Ebpf Events
         * @description Real-time Server-Sent Events (SSE) telemetry stream for eBPF kernel events.
         *     Isolates streams to authenticated tenant processes or falls back to global stream.
         *     Includes automated 15-second keepalive pings for Cloudflare Tunnel proxy buffering protection.
         */
        get: operations["stream_ebpf_events_api_v1_telemetry_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intent/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Intent Lease
         * @description Evaluates and provisions an in-kernel eBPF Intent Lease for an autonomous AI agent process.
         */
        post: operations["grant_intent_lease_api_v1_intent_lease_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intent/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Intent Leases
         * @description Lists all active kernel-enforced capability leases.
         */
        get: operations["list_intent_leases_api_v1_intent_leases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Policy From Text
         * @description Translates natural language security rules into typed eBPF/Cgroup policies via Gemini AI.
         */
        post: operations["compile_policy_from_text_api_v1_policy_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compiler/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compile Policy From Nlp
         * @description Synchronous fallback endpoint for compiler evaluations.
         */
        post: operations["compile_policy_from_nlp_api_v1_compiler_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compiler/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Compiled Rule
         * @description Directly provisions a compiled natural language rule into the active eBPF kernel policy map.
         */
        post: operations["apply_compiled_rule_api_v1_compiler_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containment/isolate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Isolate Process
         * @description Triggers automated quarantine on target process (cgroupv2 SIGSTOP) and generates forensics snapshot.
         */
        post: operations["isolate_process_api_v1_containment_isolate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containment/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release Process
         * @description Releases an isolated process back into normal execution (SIGCONT).
         */
        post: operations["release_process_api_v1_containment_release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/containment/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Incidents
         * @description Returns active and historical incident containment logs and forensics snapshots.
         */
        get: operations["get_all_incidents_api_v1_containment_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mesh/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Node
         * @description Registers an edge telemetry agent into the global control plane mesh.
         */
        post: operations["register_node_api_v1_mesh_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mesh/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Node Heartbeat
         * @description Processes liveness heartbeats and dynamic telemetry statistics from edge nodes.
         */
        post: operations["node_heartbeat_api_v1_mesh_heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mesh/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mesh Nodes
         * @description Lists all registered edge nodes, regions, and their current health status.
         */
        get: operations["list_mesh_nodes_api_v1_mesh_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Billing Usage
         * @description Returns instantaneous billing usage, event counters, and quota progress.
         */
        get: operations["api_get_billing_usage_api_v1_billing_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Create Checkout
         * @description Creates Stripe checkout session for Team Pro ($99/mo) or Enterprise ($499/mo).
         */
        post: operations["api_create_checkout_api_v1_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Stripe Webhook
         * @description Receives and verifies Stripe webhook events.
         */
        post: operations["api_stripe_webhook_api_v1_billing_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/create-checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stripe Checkout Session
         * @description Creates an authenticated Stripe Checkout Session containing metadata for automated quota boosts.
         */
        post: operations["create_stripe_checkout_session_api_v1_billing_create_checkout_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Listens for verified Stripe webhook events and automatically boosts tenant usage quotas.
         */
        post: operations["stripe_webhook_api_v1_webhook_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incident/contain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Auto Containment
         * @description Triggers sub-millisecond process freezing via cgroupv2 when a critical security violation is detected.
         */
        post: operations["trigger_auto_containment_api_v1_incident_contain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/swarm/orchestrate/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Orchestrate Swarm Stream
         * @description Real-time recursive Server-Sent Events (SSE) stream coordinating Meta-Agent delegation
         *     across dynamic clusters of specialized sub-agents.
         */
        post: operations["orchestrate_swarm_stream_api_v1_swarm_orchestrate_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/benchmark/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latency Sla Metrics
         * @description Returns real-time sub-microsecond latency distribution and kernel Ring-Buffer health indicators.
         */
        get: operations["get_latency_sla_metrics_api_v1_benchmark_latency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mesh/crdt/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Crdt State
         * @description Merges incoming CRDT policy state from peer edge nodes using Last-Write-Wins (LWW) conflict resolution.
         */
        post: operations["sync_crdt_state_api_v1_mesh_crdt_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mesh/crdt/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crdt State
         * @description Exports full local CRDT policy state for edge peer replication.
         */
        get: operations["get_crdt_state_api_v1_mesh_crdt_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cluster/crdt-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crdt Cluster Status
         * @description Returns multi-region CRDT state synchronization health and PTP timestamp synchronization.
         */
        get: operations["get_crdt_cluster_status_api_v1_cluster_crdt_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Endpoint */
        post: operations["register_endpoint_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp Endpoint */
        post: operations["verify_otp_endpoint_api_auth_verify_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Otp Endpoint */
        post: operations["resend_otp_endpoint_api_auth_resend_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Endpoint */
        post: operations["login_endpoint_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Endpoint */
        get: operations["get_me_endpoint_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Endpoint */
        post: operations["logout_endpoint_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Config */
        get: operations["oauth_config__well_known_openid_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Config */
        get: operations["oauth_config__well_known_oauth_authorization_server_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Authorize */
        get: operations["oauth_authorize_oauth_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oauth Token */
        post: operations["oauth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Real readiness: reflects live DB connectivity and real eBPF state.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/android/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Android Devices */
        get: operations["get_android_devices_api_android_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/android/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Android Summary */
        get: operations["get_android_summary_api_android_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/android/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Android Token */
        post: operations["create_android_token_api_android_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/android/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Android Command */
        post: operations["execute_android_command_api_android_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/android/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Android Policy */
        post: operations["apply_android_policy_api_android_policy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Host Metrics
         * @description Real host metrics (CPU/memory/uptime) via psutil; never fabricates values.
         */
        get: operations["api_host_metrics_api_system_host_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api System Status
         * @description Real kernel/database health snapshot from live eBPF map + PostgreSQL state.
         */
        get: operations["api_system_status_api_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Events
         * @description Returns REAL persisted security events from PostgreSQL.
         */
        get: operations["api_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Threats
         * @description Returns REAL detected threats from PostgreSQL.
         */
        get: operations["api_threats_api_threats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Metrics Stream
         * @description Authenticated Server-Sent-Events stream of real live telemetry.
         */
        get: operations["api_metrics_stream_api_metrics_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cognitive/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Cognitive State
         * @description Returns current Affective State Vector (PAD Model), Stress Index, and scaled Kernel Telemetry.
         */
        get: operations["api_cognitive_state_api_cognitive_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cognitive/stimulus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Cognitive Stimulus
         * @description Processes conversational stimulus, updates emotional state vector, creates inner monologue, and syncs to eBPF.
         */
        post: operations["api_cognitive_stimulus_api_cognitive_stimulus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cognitive/prosody": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Cognitive Prosody
         * @description Returns dynamic acoustic prosody synthesis parameters derived from the real-time Affective Vector.
         */
        get: operations["api_cognitive_prosody_api_cognitive_prosody_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cognitive/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Cognitive Stream
         * @description Real-time SSE stream broadcasting live cognitive pulses and affective state shifts.
         */
        get: operations["api_cognitive_stream_api_cognitive_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Simulate Query
         * @description Evaluates a proposed SQL query or agent mutation against active AST and kernel security policies.
         */
        post: operations["api_simulate_query_api_simulate_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/security/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Security Status
         * @description Returns active Agent-eBPF Linux kernel hooks, latency stats, and total blocked threats count.
         */
        get: operations["api_security_status_api_security_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ebpf/sock-ops/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Sock Ops Telemetry
         * @description Returns real-time socket lifecycle telemetry, database filters, and ring buffer latency stats.
         */
        get: operations["api_sock_ops_telemetry_api_ebpf_sock_ops_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sse */
        get: operations["sse_sse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Handle Mcp Messages */
        post: operations["handle_mcp_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/security-rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Add Security Rule
         * @description Adds a security rule with RBAC and token scope verification.
         */
        post: operations["api_add_security_rule_tools_security_rule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Create Portal
         * @description Generates customer billing portal session.
         */
        post: operations["api_create_portal_api_v1_billing_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forensics/simulate-dag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Api Simulate Forensics Dag
         * @description Simulates blast radius DAG, cascading table impact, and RTO downtime for a blocked query.
         */
        post: operations["api_simulate_forensics_dag_api_v1_forensics_simulate_dag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/export-manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Export Audit Manifest
         * @description Exports cryptographic SHA-256 sealed SOC-2 / HIPAA audit vault manifest for S3 partitions.
         */
        get: operations["api_export_audit_manifest_api_v1_audit_export_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/helm-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Helm Command
         * @description Generates 1-click Helm installation script for Kubernetes cluster onboarding.
         */
        get: operations["api_get_helm_command_api_v1_tenant_helm_command_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AndroidCommandRequest */
        AndroidCommandRequest: {
            /** Device Id */
            device_id: string;
            /**
             * Command Type
             * @example LOCK
             */
            command_type: string;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
        };
        /** AndroidPolicyRequest */
        AndroidPolicyRequest: {
            /**
             * Policy Id
             * @default sentinel-strict
             */
            policy_id: string;
            /**
             * Spec
             * @default {}
             */
            spec: {
                [key: string]: unknown;
            };
        };
        /** AndroidTokenRequest */
        AndroidTokenRequest: {
            /**
             * Policy Name
             * @default sentinel-strict
             */
            policy_name: string;
            /**
             * Duration Hours
             * @default 24
             */
            duration_hours: number;
        };
        /** ApplyCompiledRuleRequest */
        ApplyCompiledRuleRequest: {
            rule: components["schemas"]["CompiledRule"];
            /**
             * Pid
             * @description Optional target process ID to immediately bind the rule
             * @default 0
             */
            pid: number;
        };
        /** CRDTSyncPayload */
        CRDTSyncPayload: {
            /** Source Node Id */
            source_node_id: string;
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Tenant Id */
            tenant_id?: string | null;
            /**
             * Plan Tier
             * @default team_pro
             */
            plan_tier: string;
            /** Success Url */
            success_url?: string | null;
            /** Cancel Url */
            cancel_url?: string | null;
        };
        /** CheckoutSessionCreateRequest */
        CheckoutSessionCreateRequest: {
            /**
             * Tenant Id
             * @description Customer Tenant ID receiving quota boost
             */
            tenant_id: string;
            /**
             * Plan Tier
             * @description Subscription plan tier (pro, enterprise)
             * @default enterprise
             */
            plan_tier: string;
            /**
             * Quota Boost
             * @description Additional eBPF telemetry inspections credited
             * @default 250000
             */
            quota_boost: number;
            /**
             * Success Url
             * @default https://ksec.space/dashboard/billing?success=true
             */
            success_url: string;
            /**
             * Cancel Url
             * @default https://ksec.space/dashboard/billing?canceled=true
             */
            cancel_url: string;
        };
        /** CheckoutSessionRequest */
        CheckoutSessionRequest: {
            /**
             * Plan Tier
             * @description Target tier: developer, pro, enterprise
             * @default enterprise
             */
            plan_tier: string;
            /**
             * Success Url
             * @default https://ksec.space/dashboard/billing?session_id={CHECKOUT_SESSION_ID}
             */
            success_url: string;
            /**
             * Cancel Url
             * @default https://ksec.space/dashboard/billing?cancelled=true
             */
            cancel_url: string;
        };
        /** CognitiveStimulusRequest */
        CognitiveStimulusRequest: {
            /**
             * User Input
             * @description Conversational user message or system stimulus
             */
            user_input: string;
            /**
             * Is Mutation
             * @description Flag indicating if the action involves database mutation or critical operations
             * @default false
             */
            is_mutation: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** CompileRequest */
        CompileRequest: {
            /**
             * Query
             * @description Natural language policy prompt
             */
            query?: string | null;
            /**
             * Natural Language Rule
             * @description Natural language security intent rule
             */
            natural_language_rule?: string | null;
        };
        /** CompiledEbpfRule */
        CompiledEbpfRule: {
            /**
             * Policy Id
             * @description Unique policy identifier (e.g. pol-net-01)
             */
            policy_id: string;
            /**
             * Rule Name
             * @description Short summary description of the rule
             */
            rule_name: string;
            /**
             * Target Comm
             * @description Target process executable or binary name (e.g. python3, nc, curl)
             */
            target_comm: string;
            /**
             * Allowed Ports
             * @description List of permitted network ports
             */
            allowed_ports?: number[];
            /**
             * Protocol
             * @description Target transport layer protocol
             * @default TCP
             * @enum {string}
             */
            protocol: "TCP" | "UDP" | "ALL";
            /**
             * Action
             * @description Enforcement action verdict
             * @default ALLOW
             * @enum {string}
             */
            action: "ALLOW" | "DROP" | "LOG_ONLY";
            /**
             * Risk Level
             * @description AI evaluated threat risk level
             * @default LOW
             * @enum {string}
             */
            risk_level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Rationale
             * @description Security rationale provided by the AI compiler
             */
            rationale: string;
        };
        /** CompiledRule */
        CompiledRule: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Target Comm */
            target_comm: string;
            /** Allowed Ports */
            allowed_ports: number[];
            /** Action */
            action: string;
            /** Risk Score */
            risk_score: number;
            /** Explanation */
            explanation: string;
        };
        /** EdgeNode */
        EdgeNode: {
            /** Node Id */
            node_id: string;
            /** Hostname */
            hostname: string;
            /**
             * Region
             * @default us-east-1
             */
            region: string;
            /** Ip Address */
            ip_address: string;
            /**
             * Ebpf Probes Loaded
             * @default 1
             */
            ebpf_probes_loaded: number;
            /**
             * Active Kprobes
             * @default [
             *       "tcp_v4_connect"
             *     ]
             */
            active_kprobes: string[];
            /**
             * Cpu Usage Pct
             * @default 0
             */
            cpu_usage_pct: number;
            /**
             * Memory Mb
             * @default 0
             */
            memory_mb: number;
            /** Last Heartbeat Timestamp */
            last_heartbeat_timestamp?: number;
            /**
             * Status
             * @default ONLINE
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartbeatPayload */
        HeartbeatPayload: {
            /** Node Id */
            node_id: string;
            /**
             * Cpu Usage Pct
             * @default 0
             */
            cpu_usage_pct: number;
            /**
             * Memory Mb
             * @default 0
             */
            memory_mb: number;
        };
        /** HierarchicalSwarmRequest */
        HierarchicalSwarmRequest: {
            /**
             * Meta Agent Id
             * @description Executive Meta-Agent ID (e.g. CEO-MetaAgent-01)
             */
            meta_agent_id: string;
            /**
             * Objective
             * @description High-level enterprise strategic objective
             */
            objective: string;
            /**
             * Sub Agents
             * @description Injected specialized sub-agent swarm
             */
            sub_agents?: components["schemas"]["SubAgent"][];
        };
        /** IncidentContainmentRequest */
        IncidentContainmentRequest: {
            /**
             * Pid
             * @description Target process PID committing security violation
             */
            pid: number;
            /**
             * Comm
             * @description Binary executable name (e.g. nc, python3)
             * @default unknown
             */
            comm: string;
            /**
             * Reason
             * @description Rationale for triggering automated quarantine
             */
            reason: string;
            /**
             * Severity
             * @description Incident severity level
             * @default CRIT
             * @enum {string}
             */
            severity: "INFO" | "WARN" | "CRIT" | "crit";
        };
        /** IncidentContainmentResponse */
        IncidentContainmentResponse: {
            /** Status */
            status: string;
            /** Incident Id */
            incident_id: string;
            /** Message */
            message: string;
            /** Enforced By */
            enforced_by: string;
        };
        /** IncidentReport */
        IncidentReport: {
            /** Incident Id */
            incident_id: string;
            /** Pid */
            pid: number;
            /** Comm */
            comm: string;
            /** Reason */
            reason: string;
            /** Timestamp Ns */
            timestamp_ns: number;
            /** Action Taken */
            action_taken: string;
            /** Forensics Snapshot */
            forensics_snapshot: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default CONTAINED
             */
            status: string;
        };
        /** IntentLeaseRequest */
        IntentLeaseRequest: {
            /**
             * Intent Id
             * @description Unique Intent Identifier (e.g. intent-net-01)
             */
            intent_id: string;
            /**
             * Pid
             * @description Target Process ID running under agent execution context
             */
            pid: number;
            /**
             * Action
             * @description Policy action verdict
             * @enum {string}
             */
            action: "ALLOW" | "DENY" | "allow" | "deny";
        };
        /** IntentLeaseResponse */
        IntentLeaseResponse: {
            /**
             * Status
             * @description Execution status
             * @default success
             */
            status: string;
            /**
             * Intent Id
             * @description Granted intent identifier
             */
            intent_id: string;
            /**
             * Pid
             * @description Target Process ID
             */
            pid: number;
            /**
             * Enforced In Kernel
             * @description Whether policy was synchronized to eBPF map
             * @default true
             */
            enforced_in_kernel: boolean;
        };
        /** IsolateRequest */
        IsolateRequest: {
            /**
             * Pid
             * @description Target process PID to immediately freeze and isolate
             */
            pid: number;
            /**
             * Comm
             * @description Process name / binary executable
             * @default unknown
             */
            comm: string;
            /**
             * Reason
             * @description Containment rationale
             * @default Manual security quarantine triggered from dashboard
             */
            reason: string;
        };
        /** LatencySlaReport */
        LatencySlaReport: {
            /**
             * P50 Us
             * @description 50th percentile latency in microseconds
             */
            p50_us: number;
            /**
             * P90 Us
             * @description 90th percentile latency in microseconds
             */
            p90_us: number;
            /**
             * P99 Us
             * @description 99th percentile latency in microseconds
             */
            p99_us: number;
            /**
             * P999 Us
             * @description 99.9th percentile latency in microseconds
             */
            p999_us: number;
            /**
             * Target Sla Us
             * @description Target SLA ceiling in microseconds
             * @default 50
             */
            target_sla_us: number;
            /**
             * Sla Status
             * @description SLA compliance rating: COMPLIANT, BREACH
             * @default COMPLIANT
             */
            sla_status: string;
            /** Ring Buffer */
            ring_buffer: {
                [key: string]: unknown;
            };
            /** Active Crdt Policies */
            active_crdt_policies: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PolicyCompilationResult */
        PolicyCompilationResult: {
            /** Natural Query */
            natural_query: string;
            /** Rules */
            rules: components["schemas"]["CompiledRule"][];
            /** Overall Safety Rating */
            overall_safety_rating: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** PortalRequest */
        PortalRequest: {
            /** Tenant Id */
            tenant_id?: string | null;
            /** Return Url */
            return_url?: string | null;
        };
        /** QuerySimulateRequest */
        QuerySimulateRequest: {
            /**
             * Payload
             * @description SQL query or agent mutation to simulate
             */
            payload: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Full Name */
            full_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Company Name
             * @default Autonomous AI Corp
             */
            company_name: string | null;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /**
             * Incident Id
             * @description Target incident ID to release and unfreeze
             */
            incident_id: string;
        };
        /** ResendOtpRequest */
        ResendOtpRequest: {
            /** Email */
            email: string;
        };
        /** SimulateDAGRequest */
        SimulateDAGRequest: {
            /** Payload */
            payload: string;
            /**
             * Agent Id
             * @default langchain-db-agent
             */
            agent_id: string | null;
        };
        /** SubAgent */
        SubAgent: {
            /**
             * Agent Id
             * @description Unique sub-agent identifier
             */
            agent_id: string;
            /**
             * Role
             * @description Functional role: SECURITY, FINANCE, DEVOPS, LEGAL
             */
            role: string;
            /**
             * Model
             * @description Underlying LLM model
             * @default gemini-2.5-flash
             */
            model: string;
            /**
             * System Prompt
             * @description Domain-specific system instructions
             */
            system_prompt: string;
        };
        /** UsageResponse */
        UsageResponse: {
            /** Tenant Id */
            tenant_id: string;
            /** Plan */
            plan: string;
            /** Used Requests */
            used_requests: number;
            /** Limit */
            limit: number;
            /** Active Policies */
            active_policies: number;
            /** Latency Overhead Ms */
            latency_overhead_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyOtpRequest */
        VerifyOtpRequest: {
            /** Email */
            email: string;
            /** Otp Code */
            otp_code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stream_ebpf_events_api_v1_telemetry_stream_get: {
        parameters: {
            query?: {
                /** @description JWT Authentication token for tenant-scoped telemetry */
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_intent_lease_api_v1_intent_lease_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentLeaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentLeaseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_intent_leases_api_v1_intent_leases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    compile_policy_from_text_api_v1_policy_compile_post: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompiledEbpfRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compile_policy_from_nlp_api_v1_compiler_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyCompilationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_compiled_rule_api_v1_compiler_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyCompiledRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    isolate_process_api_v1_containment_isolate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IsolateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_process_api_v1_containment_release_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_incidents_api_v1_containment_incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentReport"][];
                };
            };
        };
    };
    register_node_api_v1_mesh_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeNode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    node_heartbeat_api_v1_mesh_heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeNode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mesh_nodes_api_v1_mesh_nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeNode"][];
                };
            };
        };
    };
    api_get_billing_usage_api_v1_billing_usage_get: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_create_checkout_api_v1_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_stripe_webhook_api_v1_billing_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_stripe_checkout_session_api_v1_billing_create_checkout_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_api_v1_webhook_stripe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_auto_containment_api_v1_incident_contain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentContainmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentContainmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orchestrate_swarm_stream_api_v1_swarm_orchestrate_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HierarchicalSwarmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latency_sla_metrics_api_v1_benchmark_latency_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatencySlaReport"];
                };
            };
        };
    };
    sync_crdt_state_api_v1_mesh_crdt_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CRDTSyncPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crdt_state_api_v1_mesh_crdt_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_crdt_cluster_status_api_v1_cluster_crdt_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_endpoint_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_endpoint_api_auth_verify_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_otp_endpoint_api_auth_resend_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendOtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_endpoint_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_endpoint_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_endpoint_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    oauth_config__well_known_openid_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    oauth_config__well_known_oauth_authorization_server_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    oauth_authorize_oauth_authorize_get: {
        parameters: {
            query?: {
                redirect_uri?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_live_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_android_devices_api_android_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_android_summary_api_android_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_android_token_api_android_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AndroidTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_android_command_api_android_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AndroidCommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_android_policy_api_android_policy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AndroidPolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_host_metrics_api_system_host_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_system_status_api_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_events_api_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_threats_api_threats_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_metrics_stream_api_metrics_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_cognitive_state_api_cognitive_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_cognitive_stimulus_api_cognitive_stimulus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CognitiveStimulusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_cognitive_prosody_api_cognitive_prosody_get: {
        parameters: {
            query?: {
                text?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_cognitive_stream_api_cognitive_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_simulate_query_api_simulate_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_security_status_api_security_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_sock_ops_telemetry_api_ebpf_sock_ops_telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sse_sse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    handle_mcp_messages_post: {
        parameters: {
            query?: {
                session_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_add_security_rule_tools_security_rule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_create_portal_api_v1_billing_portal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_simulate_forensics_dag_api_v1_forensics_simulate_dag_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateDAGRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_export_audit_manifest_api_v1_audit_export_manifest_get: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_helm_command_api_v1_tenant_helm_command_get: {
        parameters: {
            query?: {
                tenant_id?: string;
                api_key?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
